### ISSUE TITLE
Set text Typeface

### ISSUE THREAD

**Issue by gcapurro** [Cilenco/FeatureDiscovery#1]
Hi

I did some changes to allow setting the typeface and have it on a branch. In case you want to add it.

Thanks

**Comment by Cilenco** [comment]
Hey Aerim sounds great!
Please send it as pull request and I will review it.

**Comment by Aerim** [comment]
Hi, I can't I don't have access

**Comment by Cilenco** [comment]
Ah okay I think that's because you haven't forked this repo.
So for now I can't add your changed code (you haven't pushed it back to GitHub yet).

Can you maybe do it like [this](http://stackoverflow.com/a/14680805/2047987)? Would make things much easier.

**Comment by Aerim** [comment]
I think I got it, let me know how it goes so we can close this.
Regards

**Comment by Cilenco** [comment]
Great I have accepted it.
Thanks for your work!
